
[package]
name = "run"
version = "0.1.0"
authors = ["developer"]
edition = "2018"

[dependencies]
structopt = "0.3"
wasmbl = { git = "https://github.com/wasmbl/wasmbl.git", branch="main", default-features=false, features=[] }